import { motion } from "framer-motion";
import type { Briefing } from "../types";

export default function BriefingCard({ briefing }: { briefing: Briefing }) {
  return (
    <motion.section
      className="card briefing-card"
      initial={{ opacity: 0, y: 18 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      <div className="briefing-glow" aria-hidden />
      <div className="briefing-head">
        <span className="briefing-spark">✦</span>
        <span className="briefing-title">AI Briefing</span>
      </div>
      <p className="briefing-text">{briefing.text}</p>
      <span className="briefing-attrib">Generated by {briefing.model} via Groq</span>
    </motion.section>
  );
}
